version: '2.3'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins-Dockerfile
    restart: always
    volumes:
      - manager_jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
volumes:
  manager_jenkins_home:
